jira:
  project:
    workflow:
     - 'TO DO'
     - 'ANALYSIS'
     - 'IN DESIGN'
     - 'IN PROGRESS'
     - 'IN REVIEW'
     - 'IN TEST'
     - 'CONFIRMED'
     - 'DONE'

---
spring:
  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: dev

---
spring:
  config:
    activate:
      on-profile: stage

---
spring:
  config:
    activate:
      on-profile: prod