server:
  port: 80

spring:
  mvc:
    contentnegotiation:
      favor-parameter: true
    log-request-details: true

springdoc:
  api-docs:
    groups:
      enabled: true
    resolve-schema-properties: true
  group-configs:
    - group: STATISTICS
      display-name: 통계 관리
      paths-to-match: /v1/statistics/**
    - group: ACTUATOR
      display-name: Spring Actuator
      paths-to-match:
        - /actuator
        - /actuator/**
  swagger-ui:
    enabled: false
    version: v1
    groups-order: desc
    try-it-out-enabled: true
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: false
  default-produces-media-type: application/json

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true

---
spring:
  config:
    activate:
      on-profile: stage

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false