server:
  port: 81

spring:
  application:
    name: jira-statistics-indicator-itodesign

  profiles:
    include:
      - web-adapter
      - core
      - statistics-adapter
      - jira-adapters
      - statistics-jpa
      - jira-api

  devtools:
    add-properties: false
    restart:
      enabled: false

  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        xls: application/vnd.ms-excel
    log-request-details: true

  jpa:
    open-in-view: false

springdoc:
  api-docs:
    groups:
      enabled: true
    resolve-schema-properties: true
  group-configs:
    - group: STATISTICS
      display-name: 통계 관리
      paths-to-match: /v1/statistics/**
    - group: ACTUATOR
      display-name: Spring Actuator
      paths-to-match:
        - /actuator
        - /actuator/**
  swagger-ui:
    enabled: false
    version: v1
    groups-order: desc
    try-it-out-enabled: true
    display-request-duration: true
    disable-swagger-default-url: true
  show-actuator: false
  default-produces-media-type: application/json

  thymeleaf:
    cache: false
    check-template-location: false
    enabled: true
    prefix: classpath:/META-INF/resources/templates/
    suffix: .html
    view-names: /html/*