spring:
  application:
    name: jira-statistics-indicator

  profiles:
    include:
      - web-adapter
      - core
      - statistics-adapter
      - jira-adapter
      - statistics-jpa
      - jira-api

  devtools:
    add-properties: false
    restart:
      enabled: false