spring:
  devtools:
    add-properties: true
    restart:
      enabled: true

  jta:
    atomikos:
      datasource:
        statistics:
          xa-properties:
            user: root
            password: 2022ito#$
            url: "jdbc:mysql://woowahan-ito-jira-statistics.crj6fwy9fshj.ap-northeast-2.rds.amazonaws.com:3306/statistics"

springdoc:
  swagger-ui:
    enabled: true
  show-actuator: true

logging:
  config: classpath:logback-local.xml
  level:
    web: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    io.swagger.models.parameters.AbstractSerializableParameter: error