spring:
  application:
    name: jira-statistics-indicator

  profiles:
    include:
      - web-adapter
      - core
      - statistics-persistence-adapter
      - jira-rest-adapter
      - statistics-jpa
      - jira-rest-client

  devtools:
    add-properties: false
    restart:
      enabled: false